<!DOCTYPE html>
<html>
<head>
    <title>1052宿舍包裹掛號</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <h1>1052宿舍包裹掛號</h1>
        <p>105學年度第2學期 知本學苑 包裹掛號信件登記簿 (本表單僅供參考，實際簽領情形仍以紙本包裹簽領本為主)</p>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        {{ row_names|raw }}
                    </tr>
                </thead>
                <tbody>{{ row_values|raw }}</tbody>
            </table>
        </div>
    </div>
</body>
</html>
